"""核心类型定义包。

导出所有核心类型供其他模块使用。
"""

from core.types.config import (
    AgentsConfig,
    AuthConfig,
    AuthProfile,
    AuthType,
    BindMode,
    ChannelConfig,
    ChannelsConfig,
    DiscordChannelConfig,
    FeishuChannelConfig,
    GatewayConfig,
    LoggingConfig,
    LogLevel,
    ModelConfig,
    ModelProvider,
    ModelsConfig,
    SlackChannelConfig,
    TelegramChannelConfig,
    TigerClawConfig,
    TokenConfig,
)
from core.types.messages import (
    AudioContent,
    ChatRequest,
    ChatResponse,
    ContentBlock,
    ImageContent,
    Message,
    MessageChunk,
    MessageRole,
    TextContent,
    ToolResultContent,
    ToolUseContent,
)
from core.types.sessions import (
    Session,
    SessionConfig,
    SessionCreateParams,
    SessionKey,
    SessionListParams,
    SessionListResult,
    SessionMeta,
    SessionScope,
    SessionState,
)
from core.types.tools import (
    JsonSchema,
    JsonSchemaType,
    ToolCall,
    ToolDefinition,
    ToolExecutionError,
    ToolNotFoundError,
    ToolParameter,
    ToolRegistryEntry,
    ToolResult,
    ToolType,
    ToolValidationError,
)

__all__ = [
    # 消息类型
    "MessageRole",
    "TextContent",
    "ImageContent",
    "AudioContent",
    "ToolUseContent",
    "ToolResultContent",
    "ContentBlock",
    "Message",
    "MessageChunk",
    "ChatRequest",
    "ChatResponse",
    # 会话类型
    "SessionState",
    "SessionScope",
    "SessionKey",
    "SessionMeta",
    "SessionConfig",
    "Session",
    "SessionCreateParams",
    "SessionListParams",
    "SessionListResult",
    # 工具类型
    "ToolType",
    "JsonSchemaType",
    "JsonSchema",
    "ToolParameter",
    "ToolDefinition",
    "ToolCall",
    "ToolResult",
    "ToolRegistryEntry",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ToolValidationError",
    # 配置类型
    "BindMode",
    "LogLevel",
    "AuthType",
    "TokenConfig",
    "AuthConfig",
    "GatewayConfig",
    "ModelProvider",
    "AuthProfile",
    "ModelConfig",
    "ModelsConfig",
    "ChannelConfig",
    "FeishuChannelConfig",
    "SlackChannelConfig",
    "DiscordChannelConfig",
    "TelegramChannelConfig",
    "ChannelsConfig",
    "AgentConfig",
    "AgentsConfig",
    "LoggingConfig",
    "TigerClawConfig",
]
