"""定时任务服务包。

支持三种调度类型：
- at: 指定时间点执行
- every: 间隔执行（支持毫秒级）
- cron: Cron 表达式（支持时区和 stagger）

会话目标类型：
- main: 主会话执行
- isolated: 隔离会话执行
- current: 当前会话执行
- session:${id}: 指定会话执行
"""

from services.cron.agent_turn import (
    AgentTurnExecutor,
    AgentTurnPayload,
    AgentTurnResult,
    PayloadKind,
    SystemEventPayload,
    UsageSummary,
    is_agent_turn_payload,
    is_system_event_payload,
    parse_payload,
    resolve_model_override,
)
from services.cron.delivery import (
    Delivery,
    DeliveryMode,
    DeliveryPlan,
    DeliveryResult,
    DeliveryService,
    FailureDeliveryPlan,
    FailureDestination,
    get_delivery_service,
    is_same_delivery_target,
    resolve_delivery_plan,
    resolve_failure_destination,
)
from services.cron.heartbeat import (
    DEFAULT_HEARTBEAT_ACK_MAX_CHARS,
    DEFAULT_HEARTBEAT_EVERY,
    HEARTBEAT_PROMPT,
    HEARTBEAT_TOKEN,
    HeartbeatConfig,
    HeartbeatFailureAlert,
    HeartbeatMode,
    HeartbeatPolicy,
    HeartbeatState,
    StripResult,
    is_heartbeat_content_effectively_empty,
    parse_interval,
    resolve_heartbeat_prompt,
    should_enqueue_cron_main_summary,
    should_skip_heartbeat_only_delivery,
    strip_heartbeat_token,
)
from services.cron.schedule_parser import (
    clear_cron_cache,
    get_cron_cache_size,
    get_next_run,
    get_previous_run,
    is_recurring_top_of_hour_cron,
    parse_absolute_time_ms,
    parse_schedule,
    resolve_cron_stagger_ms,
    resolve_default_cron_stagger_ms,
)
from services.cron.scheduler import (
    TaskExecution,
    TaskSchedulerV2,
    TaskStatus,
    get_scheduler_v2,
)
from services.cron.session_executor import (
    IsolatedSessionContext,
    SessionExecutionContext,
    SessionExecutor,
    create_session_executor,
)
from services.cron.types import (
    AtSchedule,
    CronRunOutcome,
    CronSchedule,
    CronSessionConfig,
    EverySchedule,
    ResolvedSessionTarget,
    Schedule,
    ScheduleKind,
    ScheduleState,
    SessionTarget,
    SessionTargetKind,
    SessionTargetResolver,
    TaskDefinitionV2,
)

__all__ = [
    "AtSchedule",
    "clear_cron_cache",
    "CronSchedule",
    "EverySchedule",
    "get_cron_cache_size",
    "get_next_run",
    "get_previous_run",
    "get_scheduler_v2",
    "is_recurring_top_of_hour_cron",
    "parse_absolute_time_ms",
    "parse_schedule",
    "resolve_cron_stagger_ms",
    "resolve_default_cron_stagger_ms",
    "Schedule",
    "ScheduleKind",
    "ScheduleState",
    "TaskDefinitionV2",
    "TaskExecution",
    "TaskSchedulerV2",
    "TaskStatus",
    "Delivery",
    "DeliveryMode",
    "DeliveryPlan",
    "DeliveryResult",
    "DeliveryService",
    "FailureDeliveryPlan",
    "FailureDestination",
    "get_delivery_service",
    "is_same_delivery_target",
    "resolve_delivery_plan",
    "resolve_failure_destination",
    "ResolvedSessionTarget",
    "SessionTarget",
    "SessionTargetKind",
    "SessionTargetResolver",
    "CronSessionConfig",
    "CronRunOutcome",
    "IsolatedSessionContext",
    "SessionExecutionContext",
    "SessionExecutor",
    "create_session_executor",
    "HEARTBEAT_TOKEN",
    "HEARTBEAT_PROMPT",
    "DEFAULT_HEARTBEAT_EVERY",
    "DEFAULT_HEARTBEAT_ACK_MAX_CHARS",
    "HeartbeatMode",
    "HeartbeatConfig",
    "HeartbeatFailureAlert",
    "HeartbeatState",
    "StripResult",
    "HeartbeatPolicy",
    "is_heartbeat_content_effectively_empty",
    "resolve_heartbeat_prompt",
    "parse_interval",
    "strip_heartbeat_token",
    "should_skip_heartbeat_only_delivery",
    "should_enqueue_cron_main_summary",
    "PayloadKind",
    "UsageSummary",
    "AgentTurnResult",
    "AgentTurnPayload",
    "SystemEventPayload",
    "AgentTurnExecutor",
    "parse_payload",
    "is_agent_turn_payload",
    "is_system_event_payload",
    "resolve_model_override",
]
